### ISSUE TITLE
Implement the new Google Fonts API

### ISSUE THREAD

**Issue by manuelmeister** [CarbonPackages/Carbon.IncludeAssets#18]
Hey I just saw, that Google Fonts now supports variable fonts. This comes with an [api change](https://developers.google.com/fonts/docs/css2). The syntax & url has been modified to support more axis.

Currently the api endpoint is hardcoded here:
https://github.com/CarbonPackages/Carbon.IncludeAssets/blob/9405188c1ae94d37f855bc58126e48c7560c3735/Resources/Private/Fusion/External/GoogleFonts.fusion#L21

**Comment by jonnitto** [comment]
Hm, this would be a breaking change, I was thinking about to remove this feature, as it is not recommended to use the google font API. At least in Europe. I mean, you could include your string as just as you would include any external css file like: 
`https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata(css)`
