### ISSUE TITLE
Enable Neos 5.0

### ISSUE THREAD

**Issue by rr-appadaptive** [CarbonPackages/Carbon.IncludeAssets#9]
I tried - successfully - to install Neos from scratch yesterday. The installation of a skeleton-site as recommended by the neos-team did not work though because the necessary helper-package carbon/includeassets cannot be installed for Neos 5.0

**Comment by jonnitto** [comment]
Solved with version [3.5.1](https://github.com/CarbonPackages/Carbon.IncludeAssets/releases/tag/3.5.1)
